services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_container
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    networks:
      - ci-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - ci-network

networks:
  ci-network:

volumes:
  jenkins_home:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs: