server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

# ===============================
# JWT CONFIGURATION
# ===============================
jwt:
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:1800000}     # 30 min
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 jours

JWT_ACCESS_EXPIRATION: 3600000
JWT_REFRESH_EXPIRATION: 86400000

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}