server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    flyway:
      enabled: true


# ===============================
# JWT CONFIGURATION
# ===============================
jwt:
  access-expiration: 900000   # 15mn
  refresh-expiration: 604800000   # 7jrs
  private-key-path: ${PRIVATE_KEY_PATH:}   # variable d'env Jenkins
  public-key-path: ${PUBLIC_KEY_PATH:}     # variable d'env Jenkins

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}

app:
  url: ${APP_URL:http://localhost}
  ip: ${APP_IP:http://127.0.0.1}